# Generated by Django 5.0.4 on 2024-05-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=20)),
                ('cateogry', models.CharField(choices=[('Men', 'men'), ('Women', 'women'), ('Featured', 'featured'), ('Latest', 'latest')], max_length=20)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
